export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH';
export const UPDATE_FIELD_REGISTER = 'UPDATE_FIELD_REGISTER';
export const LOGIN = 'LOGIN';
export const CHECK_AUTH_TOKEN = 'CHECK_AUTH_TOKEN';
export const UNCHECK_AUTH_TOKEN = 'UNCHECK_AUTH_TOKEN';
export const LOGOUT = 'LOGOUT';
export const SUBMIT_AUTH_FORM = 'SUBMIT_AUTH_FORM';
export const LOADING_START = 'LOADING_START';
export const LOADING_FINISHED = 'LOADING_FINISHED';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const NEW_USER_REGISTERED = 'NEW_USER_REGISTERED';
export const REDIRECTED_TO_LOGIN_FORM = 'REDIRECTED_TO_LOGIN_FORM';
export const REGISTER = 'REGISTER';

export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const UPDATE_MESSAGE_FIELD = 'UPDATE_MESSAGE_FIELD';
export const MESSAGE_SENT = 'MESSAGE_SENT';
export const SCROLL_MESSAGES = 'SCROLL_MESSAGES';
export const START_LOADING_MESSAGES = 'START_LOADING_MESSAGES';
export const FINISH_LOADING_MESSAGES = 'FINISH_LOADING_MESSAGES';
export const RESET_UNREAD_MESSAGES_COUNTER = 'RESET_UNREAD_MESSAGES_COUNTER';

export const GIPHY_MODAL_SHOW = 'GIPHY_MODAL_SHOW';
export const GIPHY_MODAL_CLOSE = 'GIPHY_MODAL_CLOSE';
export const CHANGE_GIPHY_SEARCH_QUERY = 'CHANGE_GIPHY_SEARCH_QUERY';
export const LOAD_GIPHYS_LIST = 'LOAD_GIPHYS_LIST';
export const LOAD_MORE_GIPHYS = 'LOAD_MORE_GIPHYS';